/*
Andressa Yida Pinheiro de Souza
Willian Yoshio Murayama
Projeto semestral de programacao orientado a objetos
 */
package Interface;

import Controle.Controle;

public class CadastroFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form NovoCadastro
     */
    public CadastroFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        FuncaoTitulacaoLabel.setVisible(false);
        FuncaoTitulacaoJBox.setVisible(false);
        CargaHorariaAreaJBox.setVisible(false);
        CargaHorariaAreaLabel.setVisible(false);
        CadastroRepetido.setText("Digite o código");
        Cadastrar.setEnabled(false);
        CadastroSucesso.setVisible(false);
        if (Controle.getQuantidadeDepartameto() == 0) {
            CadastroRepetido.setText("Cadastre um departamento");
            Cadastrar.setEnabled(false);
        }
    }

    public void ListaDepartamento(String Item) {
        Departamento.addItem(Item);
    }
    Controle Controle = new Controle();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoriaBox = new javax.swing.JComboBox<>();
        NivelBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Codigo = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Nome = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Salario = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Cadastrar = new javax.swing.JButton();
        FuncaoTitulacaoLabel = new javax.swing.JLabel();
        FuncaoTitulacaoJBox = new javax.swing.JComboBox<>();
        CargaHorariaAreaLabel = new javax.swing.JLabel();
        CargaHorariaAreaJBox = new javax.swing.JComboBox<>();
        Departamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CadastroRepetido = new javax.swing.JLabel();
        CadastroSucesso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo cadastro");

        CategoriaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma categoria", "Tecnico", "Docente efetivo", "Docente substituto" }));
        CategoriaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaBoxActionPerformed(evt);
            }
        });

        NivelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um nível" }));
        NivelBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelBoxActionPerformed(evt);
            }
        });

        Codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CodigoFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(Codigo);

        jScrollPane2.setViewportView(Nome);

        Salario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SalarioFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(Salario);

        jLabel1.setText("Código");

        jLabel2.setText("Salário");

        jLabel3.setText("Nome");

        jLabel4.setText("Nível");

        jLabel5.setText("Categoria");

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        FuncaoTitulacaoLabel.setText("Área");

        CargaHorariaAreaLabel.setText("Carga horária do substituto");

        CargaHorariaAreaJBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "24" }));

        Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentoActionPerformed(evt);
            }
        });

        jLabel6.setText("Departamento");

        CadastroRepetido.setText("jLabel7");

        CadastroSucesso.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(CategoriaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(FuncaoTitulacaoLabel)
                                .addComponent(CargaHorariaAreaLabel)
                                .addComponent(jLabel6)
                                .addComponent(Departamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NivelBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FuncaoTitulacaoJBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CargaHorariaAreaJBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 123, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CadastroRepetido)
                            .addComponent(CadastroSucesso))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CadastroRepetido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CategoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NivelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FuncaoTitulacaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FuncaoTitulacaoJBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CargaHorariaAreaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CargaHorariaAreaJBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CadastroSucesso)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NivelBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NivelBoxActionPerformed

    private void CategoriaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaBoxActionPerformed
        // TODO add your handling code here:
        switch (CategoriaBox.getSelectedItem().toString()) {
            case "Selecione uma categoria":
                NivelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Selecione um nível"}));
                CargaHorariaAreaJBox.setVisible(false);
                CargaHorariaAreaLabel.setVisible(false);
                FuncaoTitulacaoLabel.setVisible(false);
                FuncaoTitulacaoJBox.setVisible(false);
                break;
            case "Tecnico":
                NivelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"T1", "T2"}));
                FuncaoTitulacaoLabel.setText("Função");
                FuncaoTitulacaoJBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Assesor", "Laboratorio", "Secretario"}));
                CargaHorariaAreaJBox.setVisible(false);
                CargaHorariaAreaLabel.setVisible(false);
                FuncaoTitulacaoLabel.setVisible(true);
                FuncaoTitulacaoJBox.setVisible(true);
                break;
            case "Docente efetivo":
                NivelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"D1", "D2", "D3"}));
                FuncaoTitulacaoJBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Graduacao", "Mestrado", "Doutorado", "Livre-docente"}));
                FuncaoTitulacaoLabel.setText("Titulação");
                CargaHorariaAreaLabel.setText("Área");
                CargaHorariaAreaJBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Biologicas", "Exatas", "Humanas", "Saude"}));
                CargaHorariaAreaJBox.setVisible(true);
                CargaHorariaAreaLabel.setVisible(true);
                FuncaoTitulacaoLabel.setVisible(true);
                FuncaoTitulacaoJBox.setVisible(true);
                break;
            case "Docente substituto":
                NivelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"S1", "S2"}));
                FuncaoTitulacaoJBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Graduacao", "Mestrado", "Doutorado", "Livre-docente"}));
                FuncaoTitulacaoLabel.setText("Titulação");
                CargaHorariaAreaLabel.setText("Carga horária");
                CargaHorariaAreaJBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"12", "24"}));
                CargaHorariaAreaJBox.setVisible(true);
                CargaHorariaAreaLabel.setVisible(true);
                FuncaoTitulacaoLabel.setVisible(true);
                FuncaoTitulacaoJBox.setVisible(true);
                break;
        }
    }//GEN-LAST:event_CategoriaBoxActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        String codigo, nome, categoria, nivel, funcao, area, titulacao;
        int cargaHoraria;
        double salario;

        switch (CategoriaBox.getSelectedItem().toString()) {
            case "Selecione uma categoria":
                CadastroRepetido.setText("Selecione uma categoria");
            case "Tecnico":
                codigo = Codigo.getText();
                nome = Nome.getText();
                salario = Double.parseDouble(Salario.getText());
                categoria = CategoriaBox.getSelectedItem().toString();
                nivel = NivelBox.getSelectedItem().toString();
                funcao = FuncaoTitulacaoJBox.getSelectedItem().toString();
                Controle.cadastrarTecnico(codigo, nome, salario, categoria, nivel, funcao, Departamento.getSelectedItem().toString());
                CadastroSucesso.setText("Funcionário cadastrado com sucesso");
                CadastroSucesso.setVisible(true);
                break;
            case "Docente efetivo":
                codigo = Codigo.getText();
                nome = Nome.getText();
                salario = Double.parseDouble(Salario.getText());
                categoria = CategoriaBox.getSelectedItem().toString();
                nivel = NivelBox.getSelectedItem().toString();
                titulacao = FuncaoTitulacaoJBox.getSelectedItem().toString();
                area = CargaHorariaAreaJBox.getSelectedItem().toString();
                Controle.cadastrarDocenteEfetivo(codigo, nome, salario, categoria, nivel, Departamento.getSelectedItem().toString(), titulacao, area);
                CadastroSucesso.setText("Funcionário cadastrado com sucesso");
                CadastroSucesso.setVisible(true);
                break;
            case "Docente substituto":
                codigo = Codigo.getText();
                nome = Nome.getText();
                salario = Double.parseDouble(Salario.getText());
                categoria = CategoriaBox.getSelectedItem().toString();
                nivel = NivelBox.getSelectedItem().toString();
                titulacao = FuncaoTitulacaoJBox.getSelectedItem().toString();
                cargaHoraria = Integer.parseInt(CargaHorariaAreaJBox.getSelectedItem().toString());
                Controle.cadastrarDocenteSubstituto(codigo, nome, salario, categoria, nivel, Departamento.getSelectedItem().toString(), titulacao, cargaHoraria);
                CadastroSucesso.setText("Funcionário cadastrado com sucesso");
                CadastroSucesso.setVisible(true);
                break;
        }

    }//GEN-LAST:event_CadastrarActionPerformed

    private void DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartamentoActionPerformed

    private void CodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CodigoFocusLost
        // TODO add your handling code here:
        if (Controle.getQuantidadeDepartameto() == 0) {
            CadastroRepetido.setText("Cadastre um departamento");
            Cadastrar.setEnabled(false);
        } else if (Controle.codigoRepetidoFuncionario(Codigo.getText()) || Codigo.getText().equals("")) {
            CadastroRepetido.setText("Código indisponível");
            Cadastrar.setEnabled(false);
        } else {
            CadastroRepetido.setText("Código disponível");
            Cadastrar.setEnabled(true);
        }
    }//GEN-LAST:event_CodigoFocusLost

    private void SalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SalarioFocusLost
        // TODO add your handling code here:
//        if (!Salario.getText().matches("[0-9.]+")) {;
//            Cadastrar.setEnabled(false);
//            Cadastrar.setText("Salário inválido");
//        } else {
//            Cadastrar.setEnabled(true);
//            Cadastrar.setText("Cadastrar");
//        }
    }//GEN-LAST:event_SalarioFocusLost

    private void CodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CodigoFocusGained
        // TODO add your handling code here:
        CadastroSucesso.setVisible(false);
    }//GEN-LAST:event_CodigoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroFuncionario dialog = new CadastroFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JLabel CadastroRepetido;
    private javax.swing.JLabel CadastroSucesso;
    private javax.swing.JComboBox<String> CargaHorariaAreaJBox;
    private javax.swing.JLabel CargaHorariaAreaLabel;
    private javax.swing.JComboBox<String> CategoriaBox;
    private javax.swing.JTextPane Codigo;
    private javax.swing.JComboBox<String> Departamento;
    private javax.swing.JComboBox<String> FuncaoTitulacaoJBox;
    private javax.swing.JLabel FuncaoTitulacaoLabel;
    private javax.swing.JComboBox<String> NivelBox;
    private javax.swing.JTextPane Nome;
    private javax.swing.JTextPane Salario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
