/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controle.Controle;

/**
 *
 * @author Willian
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form IUPrincipal
     */
    public Principal() {
        initComponents();
    }

    public static void main(String[] args) {;
        Interface.Principal InterfaceMenu = new Interface.Principal();
        InterfaceMenu.setVisible(true);
        InterfaceMenu.setTitle("Sistema faculdade");
        InterfaceMenu.toFront();
    }
    Controle Controle = new Controle();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraDeMenu = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        CadastroFuncionario = new javax.swing.JMenuItem();
        CadastroDepartamento = new javax.swing.JMenuItem();
        Relatorio = new javax.swing.JMenu();
        Geral = new javax.swing.JMenuItem();
        ResumoDepartamento = new javax.swing.JMenuItem();
        ResumoDepartamentoGasto = new javax.swing.JMenuItem();
        FuncionarioSalarioEspecifico = new javax.swing.JMenuItem();
        Exibir = new javax.swing.JMenu();
        TodosFuncionarios = new javax.swing.JMenuItem();
        TodosTecnicos = new javax.swing.JMenuItem();
        TodosDocentes = new javax.swing.JMenuItem();
        TodosDocentesEfetivos = new javax.swing.JMenuItem();
        TodosDocentesSubstitutos = new javax.swing.JMenuItem();
        InformacoesDepartamento = new javax.swing.JMenuItem();
        Buscar = new javax.swing.JMenu();
        FuncionarioCodigo = new javax.swing.JMenuItem();
        FuncionarioNome = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Faculdade");

        Cadastro.setText("Cadastro");
        Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroActionPerformed(evt);
            }
        });

        CadastroFuncionario.setActionCommand("Novo cadastro de funcionario");
        CadastroFuncionario.setLabel("Novo cadastro de funcionário");
        CadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroFuncionarioActionPerformed(evt);
            }
        });
        Cadastro.add(CadastroFuncionario);

        CadastroDepartamento.setText("Novo cadastro de departamento");
        CadastroDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroDepartamentoActionPerformed(evt);
            }
        });
        Cadastro.add(CadastroDepartamento);

        BarraDeMenu.add(Cadastro);

        Relatorio.setText("Relatório");

        Geral.setText("Geral");
        Geral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeralActionPerformed(evt);
            }
        });
        Relatorio.add(Geral);

        ResumoDepartamento.setText("Resumo dos departamentos");
        ResumoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumoDepartamentoActionPerformed(evt);
            }
        });
        Relatorio.add(ResumoDepartamento);

        ResumoDepartamentoGasto.setText("Resumo dos departamentos com gasto em faixa específica");
        ResumoDepartamentoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumoDepartamentoGastoActionPerformed(evt);
            }
        });
        Relatorio.add(ResumoDepartamentoGasto);

        FuncionarioSalarioEspecifico.setText("Funcionários com salário em faixa específica");
        Relatorio.add(FuncionarioSalarioEspecifico);

        BarraDeMenu.add(Relatorio);

        Exibir.setText("Exibir");

        TodosFuncionarios.setText("Todos os funcionários");
        TodosFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosFuncionariosActionPerformed(evt);
            }
        });
        Exibir.add(TodosFuncionarios);

        TodosTecnicos.setText("Todos os técnicos");
        TodosTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosTecnicosActionPerformed(evt);
            }
        });
        Exibir.add(TodosTecnicos);

        TodosDocentes.setText("Todos os docentes");
        TodosDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosDocentesActionPerformed(evt);
            }
        });
        Exibir.add(TodosDocentes);

        TodosDocentesEfetivos.setText("Todos os docentes efetivos");
        TodosDocentesEfetivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosDocentesEfetivosActionPerformed(evt);
            }
        });
        Exibir.add(TodosDocentesEfetivos);

        TodosDocentesSubstitutos.setText("Todos os docentes substitutos");
        TodosDocentesSubstitutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosDocentesSubstitutosActionPerformed(evt);
            }
        });
        Exibir.add(TodosDocentesSubstitutos);

        InformacoesDepartamento.setText("Informações de um departamento");
        InformacoesDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacoesDepartamentoActionPerformed(evt);
            }
        });
        Exibir.add(InformacoesDepartamento);

        BarraDeMenu.add(Exibir);

        Buscar.setText("Buscar");

        FuncionarioCodigo.setText("Funcionários pelo código");
        FuncionarioCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionarioCodigoActionPerformed(evt);
            }
        });
        Buscar.add(FuncionarioCodigo);

        FuncionarioNome.setText("Funcionários pelo nome");
        FuncionarioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionarioNomeActionPerformed(evt);
            }
        });
        Buscar.add(FuncionarioNome);

        BarraDeMenu.add(Buscar);

        setJMenuBar(BarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CadastroActionPerformed

    private void GeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeralActionPerformed
        // TODO add your handling code here:
        Relatorio RelatorioInterface = new Relatorio(this, true);
        RelatorioInterface.setLocationRelativeTo(this);
        RelatorioInterface.setVisible(true);
    }//GEN-LAST:event_GeralActionPerformed

    private void CadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroFuncionarioActionPerformed
        // TODO add your handling code here:

        CadastroFuncionario NovoCadastroInterface = new CadastroFuncionario(this, true);
//        Controle Controle = new Controle();
        int Quantidade = Controle.getQuantidadeDepartameto();
        for (int i = 0; i < Quantidade; i++) {
            NovoCadastroInterface.ListaDepartamento(Controle.getDepartamentoNome(i));
        }
        NovoCadastroInterface.setTitle("Novo cadastro de funcionário");
        NovoCadastroInterface.setLocationRelativeTo(this);
        NovoCadastroInterface.setVisible(true);
    }//GEN-LAST:event_CadastroFuncionarioActionPerformed

    private void TodosTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosTecnicosActionPerformed
        // TODO add your handling code here:
//        Controle Controle = new Controle();
        ResumoDepartamento ExibitInterface = new ResumoDepartamento(this, true);
        ExibitInterface.setTitle("Todos os técnicos");
        ExibitInterface.alterarTexto("Todos os técnicos", Controle.exibirTodosTecnicos());
        ExibitInterface.setLocationRelativeTo(this);
        ExibitInterface.setVisible(true);
    }//GEN-LAST:event_TodosTecnicosActionPerformed

    private void CadastroDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroDepartamentoActionPerformed
        // TODO add your handling code here:
        CadastroDepartamento CadastroDepartamentoInterface = new CadastroDepartamento(this, true);
        CadastroDepartamentoInterface.setTitle("Novo cadastro de departamento");
        CadastroDepartamentoInterface.setLocationRelativeTo(this);
        CadastroDepartamentoInterface.setVisible(true);
    }//GEN-LAST:event_CadastroDepartamentoActionPerformed

    private void ResumoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumoDepartamentoActionPerformed
        // TODO add your handling code here:
//        Controle Controle = new Controle();
        ResumoDepartamento ExibitInterface = new ResumoDepartamento(this, true);
        ExibitInterface.alterarTexto("Resumo dos departamentos", Controle.exibirTodosDepartamentos()
        );
        ExibitInterface.setTitle("Resumo dos departamentos");

        ExibitInterface.setLocationRelativeTo(this);
        ExibitInterface.setVisible(true);
    }//GEN-LAST:event_ResumoDepartamentoActionPerformed

    private void FuncionarioCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionarioCodigoActionPerformed
        // TODO add your handling code here:
        BuscaCodigo BuscarInterface = new BuscaCodigo(this, true);
        BuscarInterface.setTitle("Buscar pelo código");
        BuscarInterface.Exibir("Buscar pelo código");
        BuscarInterface.setLocationRelativeTo(this);
        BuscarInterface.setVisible(true);
    }//GEN-LAST:event_FuncionarioCodigoActionPerformed

    private void FuncionarioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionarioNomeActionPerformed
        // TODO add your handling code here:
        BuscaNome BuscarInterface = new BuscaNome(this, true);
        BuscarInterface.setTitle("Buscar pelo nome");
        BuscarInterface.Exibir("Buscar pelo nome");
        BuscarInterface.setLocationRelativeTo(this);
        BuscarInterface.setVisible(true);
    }//GEN-LAST:event_FuncionarioNomeActionPerformed

    private void TodosFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosFuncionariosActionPerformed
        // TODO add your handling code here:

//        Controle Controle = new Controle();
        ResumoDepartamento ExibitInterface = new ResumoDepartamento(this, true);
        ExibitInterface.alterarTexto("Todos os funcionários", Controle.exibirTodosFuncionarios());
        ExibitInterface.setTitle("Todos os funcionários");
        ExibitInterface.setLocationRelativeTo(this);
        ExibitInterface.setVisible(true);

    }//GEN-LAST:event_TodosFuncionariosActionPerformed

    private void TodosDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosDocentesActionPerformed
        // TODO add your handling code here:
//        Controle Controle = new Controle();
        ResumoDepartamento ExibitInterface = new ResumoDepartamento(this, true);
        ExibitInterface.setTitle("Todos os docentes");
        ExibitInterface.setLocationRelativeTo(this);
        ExibitInterface.setVisible(true);
    }//GEN-LAST:event_TodosDocentesActionPerformed

    private void TodosDocentesEfetivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosDocentesEfetivosActionPerformed
        // TODO add your handling code here:
//        Controle Controle = new Controle();
        ResumoDepartamento ExibitInterface = new ResumoDepartamento(this, true);
        ExibitInterface.setTitle("Todos os docentes efetivos");
        ExibitInterface.alterarTexto("Todos os docentes efetivos", Controle.exibirTodosDocentesEfetivos());
        ExibitInterface.setLocationRelativeTo(this);
        ExibitInterface.setVisible(true);
    }//GEN-LAST:event_TodosDocentesEfetivosActionPerformed

    private void TodosDocentesSubstitutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosDocentesSubstitutosActionPerformed
        // TODO add your handling code here:
//        Controle Controle = new Controle();
        ResumoDepartamento ExibitInterface = new ResumoDepartamento(this, true);
        ExibitInterface.setTitle("Todos os docentes substitutos");
        ExibitInterface.alterarTexto("Todos os docentes substitutos", Controle.exibirTodosDocentesSubstitutos());
        ExibitInterface.setLocationRelativeTo(this);
        ExibitInterface.setVisible(true);
    }//GEN-LAST:event_TodosDocentesSubstitutosActionPerformed

    private void InformacoesDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacoesDepartamentoActionPerformed
        // TODO add your handling code here:
//        Controle Controle = new Controle();
        InformacoesDepartamento Informacoes = new InformacoesDepartamento(this, true);
        Informacoes.setTitle("Informações de um departamento");
        Informacoes.setLocationRelativeTo(this);
        Informacoes.setVisible(true);
    }//GEN-LAST:event_InformacoesDepartamentoActionPerformed

    private void ResumoDepartamentoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumoDepartamentoGastoActionPerformed
        // TODO add your handling code here:
        ResumoDepartamentoBusca ResumoGasto = new ResumoDepartamentoBusca(this, true);
        ResumoGasto.setTitle("Busca de departamento com gasto específico");
        ResumoGasto.setLocationRelativeTo(this);
        ResumoGasto.setVisible(true);
    }//GEN-LAST:event_ResumoDepartamentoGastoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenu;
    private javax.swing.JMenu Buscar;
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem CadastroDepartamento;
    private javax.swing.JMenuItem CadastroFuncionario;
    private javax.swing.JMenu Exibir;
    private javax.swing.JMenuItem FuncionarioCodigo;
    private javax.swing.JMenuItem FuncionarioNome;
    private javax.swing.JMenuItem FuncionarioSalarioEspecifico;
    private javax.swing.JMenuItem Geral;
    private javax.swing.JMenuItem InformacoesDepartamento;
    private javax.swing.JMenu Relatorio;
    private javax.swing.JMenuItem ResumoDepartamento;
    private javax.swing.JMenuItem ResumoDepartamentoGasto;
    private javax.swing.JMenuItem TodosDocentes;
    private javax.swing.JMenuItem TodosDocentesEfetivos;
    private javax.swing.JMenuItem TodosDocentesSubstitutos;
    private javax.swing.JMenuItem TodosFuncionarios;
    private javax.swing.JMenuItem TodosTecnicos;
    // End of variables declaration//GEN-END:variables
}
